pronouns = {
    "1st Person",
    "2nd Person",
    "3rd Person",
    "4th Person",
    "Undefined",
    "Us (excluding you)",
    "Us (including you)",
    "Y'all",
    "They",
}

tense = {
    "Past Tense",
    "Present Tense",
    "Future Tense",
    "Transistive (I want)",
}

form = {
    "A form",
    "B form",
    "C form",
}

word_bank_nish = {
    "Ayaa",
    "Gaasknaabaagwe",
    "Bakade",
    "Wiisini",
    "Minikwe",
    "Mino'zhiyaa",
    "Aakozi",
    "Izhaa",
    "Dagoshin",
    "Maajaa",
    "Bizhaa",
    "Pskaabii",
    "Nibaa",
    "Goshkozi",
    "Bizigwii",
    "Zhiishiigi",
    "Zaakam",
    "Miizii",
    "Giziibiigiingwe",
    "Giziibiigzhe",
    "Biiskonye",
    "Nsikwewa",
    "Giziiyaabdewa",
    "Kizhebaa'wiisini",
    "Anakii",
    "Naakwe'wiisini",
    "Giiwe",
    "Naagshi'wiisini",
    "Giiskonye",
    "Wiinchige",
    "Biinchige",
    "Giziigbiignaagne",
    "Giziibiignige",
    "Gziisga'ge",
    "Jiigda'ge",
    "Bagiza",
    "Zhooshkwaade",
    "Giigoonke",
    "Giiwse",
    "Bibaambatoo",
    "Bibaamase",
    "Baayaajige",
    "Naajmiijme",
    "Bibaambiza",
    "Bibaamwebshkige",
    "Midwewechige",
    "Gitige",
    "Minidoomnenske",
    "Gaawyeke",
    "Niimi",
}

word_bank_eng = {
    "S/he is (located s.where)",
    "S/he is thirsty",
    "S/he is hungry",
    "S/he eats",
    "S/he drinks",
    "S/he is doing/feels well",
    "S/he is sick",
    "S/he goes (s.where)",
    "S/he arrives (s.where)",
    "S/he leaves",
    "S/he comes",
    "S/he returns",
    "S/he sleeps",
    "S/he wakes up/is awake",
    "S/he gets up",
    "S/he pees/urinates",
    "S/he goes to the bathroom/pees",
    "S/he poops",
    "S/he washes h/ face",
    "S/he bathes",
    "S/he gets dressed/puts on h/ clothes",
    "S/he brushes h/ hair",
    "S/he brushes h/ teeth",
    "S/he eats breakfast",
    "S/he works",
    "S/he eats lunch",
    "S/he goes home",
    "S/he eats diner",
    "S/he gets undressed/takes off h/ clothes",
    "S/he makes a mess",
    "S/he cleans",
    "S/he does the dishes/washes the dishes",
    "S/he does (the) laundry/washes clothes",
    "S/he washes/scrubs the floor",
    "S/he sweeps",
    "S/he swims",
    "S/he skates/plays hockey",
    "S/he fishes",
    "S/he hunts",
    "S/he runs/jogs",
    "S/he goes for (a) walk(s)",
    "S/he shops",
    "S/he goes to get groceries/food",
    "S/he drives/rides around",
    "S/he goes for a bike ride",
    "S/he plays music",
    "S/he gardens",
    "S/he beads",
    "S/he does quillwork",
    "S/he dances",
}

